### ISSUE TITLE
Fixed LSL script

### ISSUE THREAD

**Issue by ghost** [jgpippin/sldb#4]
There were some little errors in the functions to read  and delete, and the url shoulr end with / for the script to work. And the uuid field in the database was 4 characters short (The ---- ) so it was impossible to retreive data with the example script.
Not sure how its done but i forked and edited the scripts.
Ty and good work!

**Comment by jgpippin** [comment]
I think the script may have been written for a different version of PHP than is generally current, as this used to run without error.

I was most lately working on a JSON-based alternative that required more functions be included on the LSL side, but that allowed the user to set and unset parameters more elegantly.

I'll have a look at your commit and see about wrapping it in to the original product and crediting you. If I do that, would you be willing to remove your fork from the reviews so there isn't confusion about which to use?

On October 7, 2015 at 9:39:06 AM, burt-artis (notifications@github.com) wrote:

There were some little errors in the functions to read and delete, and the url shoulr end with / for the script to work. And the uuid field in the database was 4 characters short (The ---- ) so it was impossible to retreive data with the example script.
Not sure how its done but i forked and edited the scripts.
Ty and good work!

**Comment by ghost** [comment]
done,

**Comment by jgpippin** [comment]
Oh, I wasn't asking you to remove the review! It was a legitimate comment on the level of difficulty and your fork is valuable to other people looking at the product while my version is still broken. I was just asking you to edit the review after I'd included your fixes to point folks back to the original product.
.

On October 7, 2015 at 11:04:20 AM, burt-artis (notifications@github.com) wrote:

done,
